# Generated by Django 4.0.3 on 2022-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_rename_paymentdetails1_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='sms.student'),
        ),
    ]
