# Generated by Django 4.0.3 on 2022-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('delhi', 'Delhi'), ('noida', 'Noida'), ('hisar', 'Hisar'), ('rohtak', 'Rohtak')], default='delhi', max_length=6)),
                ('age', models.CharField(max_length=15)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
