# Generated by Django 4.0.3 on 2022-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
